import {escapeHtml as e} from '../../../shared/render/html.mjs';
export function renderPage(s,images,resources){
 const base=s.route;
 const img=(id,cls='',eager=false)=>{const a=images[id];return `<img class="${cls}" src="${base}${a.src}" srcset="${a.variants.map(v=>`${base}${v.src} ${v.width}w`).join(', ')}" sizes="(max-width: 700px) 90vw, 45vw" width="${a.width}" height="${a.height}" alt="${e(a.alt)}" loading="${eager?'eager':'lazy'}" ${eager?'fetchpriority="high"':''} decoding="async">`;};
 const photo=(id,caption,cls='',eager=false)=>`<figure class="paper ${cls}">${img(id,'',eager)}<figcaption>${caption}</figcaption></figure>`;
 const film=(id,label)=>{const f=s.films.find(f=>f.sourceAssetId===id);return `<figure class="film paper" data-film><video controls muted playsinline loop preload="none" width="${f.width}" height="${f.height}" poster="${base}${f.posterSrc}" aria-label="${e(label)}"><source src="${base}${f.src}" type="video/mp4"></video><img data-film-fallback hidden src="${base}${f.posterSrc}" width="${f.width}" height="${f.height}" alt="${e(f.posterAlt)}"><span role="status"></span><figcaption>${e(label)}</figcaption></figure>`;};
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="A Round with Sienna. Discover Swing × Sienna Hartley and a collection made for days on and off the course."><title>A Round with Sienna — Swing × Sienna Hartley</title><link rel="stylesheet" href="${base}${resources.style}"><script type="module" src="${base}${resources.script}"></script></head><body><a class="skip" href="#story">Skip to the story</a>
<header class="masthead"><span class="wordmark">swing</span><span class="edition">THE COLLABORATION ISSUE</span><span class="tiny">SWING × SIENNA HARTLEY</span></header>
<main><section class="hero" aria-labelledby="title"><div class="hero-heading"><p class="eyebrow">A little coastal. A little clubhouse.</p><h1 id="title">A Round<br><span>with <i>Sienna</i></span></h1><p class="hero-note handwriting">Meet you on the green.</p></div><div class="hero-collage">${photo('C19','01 / A day worth dressing for.','hero-main',true)}${photo('C02','Good company, great rounds.','hero-friends',true)}${photo('C01','Just one more round.','hero-detail')}<span class="vertical-note">THE COURSE IS CALLING</span></div><div class="hero-bottom"><p>Sienna’s relaxed coastal style,<br>made for days on and off the course.</p><a class="text-link" href="#story">Discover the collection <span aria-hidden="true">↘</span></a></div></section>
<section class="intro section" id="story"><p class="eyebrow">SWING × SIENNA HARTLEY</p><h2>Come for the round.<br><i>Stay for the afternoon.</i></h2><p>For our collaboration with Sienna Hartley, we’re taking the scenic route. A love of golf, an easy coastal spirit, and a little room to linger. Consider this your invitation.</p><span class="handwriting">No rush. Just a good day.</span></section>
<section class="moments section" aria-labelledby="first-tee"><div class="section-label"><span>01 / THE FIRST TEE</span><h2 id="first-tee">A softer kind of sporting life.</h2></div><div class="moment-grid">${photo('C14','A fresh start.','moment-left')}${film('V01','A moment between rounds.')}${photo('C21','A little sunshine goes a long way.','moment-right')}</div></section>
<section class="details section" aria-labelledby="details-title"><div class="section-label"><span>02 / THE DETAILS</span><h2 id="details-title">Three pieces. <i>One easy feeling.</i></h2></div><div class="detail-grid">${s.products.map((p,i)=>`<article><span class="number">0${i+1}</span>${img(p.images[0])}<h3>${e(p.name)}</h3><p>${e(p.eyebrow)}</p></article>`).join('')}</div></section>
<section class="afternoon section" aria-labelledby="afternoon-title"><div class="afternoon-title"><p class="eyebrow">03 / TAKING THE LONG WAY HOME</p><h2 id="afternoon-title">Nothing on the agenda.<br><i>Except a little more sun.</i></h2><p>Good rounds have a way of becoming whole afternoons. That’s the spirit of this collaboration: relaxed, considered, and entirely at home beyond the course.</p></div><div class="afternoon-grid">${photo('C20','That late-afternoon feeling.','sunshine')}${film('V03','Time for a little pause.')}${photo('C09','The scenic route, always.','cart')}</div><p class="handwriting afternoon-note">Let’s stay a little longer.</p></section>
<section class="collection section" id="collection" aria-labelledby="collection-title"><p class="eyebrow">THE SWING × SIENNA HARTLEY COLLECTION</p><h2 id="collection-title">Take the feeling <i>with you.</i></h2><p class="collection-intro">From the first tee to whatever comes after.</p><div class="product-grid">${s.products.map(p=>`<article class="product">${img(p.images[0],'product-front')}<div class="product-heading"><h3>${e(p.name)}</h3><span>SWING × SIENNA</span></div><p>${e(p.description)}</p><details><summary>See the back <span aria-hidden="true">+</span></summary>${img(p.images[1])}</details></article>`).join('')}</div><p class="shop-label">Shop the collection</p></section>
<section class="closing"><div><p class="eyebrow">UNTIL THE NEXT ROUND</p><h2>See you<br><i>on the green.</i></h2><p class="handwriting">With love, Swing.</p></div>${photo('C03','A day well spent.')}</section></main><footer><span>SWING × SIENNA HARTLEY</span><a href="#title">Back to the beginning ↑</a></footer></body></html>`;
}
