import {escapeHtml as e} from '../../../shared/render/html.mjs';
export function renderPage(s,images,resources){
 const base=s.route;
 const img=(id,cls='',eager=false)=>{const a=images[id];return `<img class="${cls}" src="${base}${a.src}" srcset="${a.variants.map(v=>`${base}${v.src} ${v.width}w`).join(', ')}" sizes="(max-width: 700px) 92vw, 48vw" width="${a.width}" height="${a.height}" alt="${e(a.alt)}" loading="${eager?'eager':'lazy'}" ${eager?'fetchpriority="high"':''} decoding="async">`;};
 const film=(id,label)=>{const f=s.films.find(f=>f.sourceAssetId===id);return `<figure class="film" data-film><video src="${base}${f.src}" controls muted playsinline loop preload="none" width="${f.width}" height="${f.height}" poster="${base}${f.posterSrc}" aria-label="${e(label)}"></video><img data-film-fallback hidden src="${base}${f.posterSrc}" width="${f.width}" height="${f.height}" alt="${e(f.posterAlt)}"><span role="status"></span><figcaption>${e(label)}</figcaption></figure>`;};
 const cta=label=>`<a class="cta" href="#collection">${label}<span aria-hidden="true">↗</span></a>`;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="Meet Swing Tennis. The same confidence, personality, and community, now on a new court."><title>This is a test — Swing Tennis</title><link rel="stylesheet" href="${base}${resources.style}"><script type="module" src="${base}${resources.script}"></script></head><body><a class="skip" href="#main">Skip to content</a>
<header class="masthead"><span class="wordmark">swing<span class="wordmark-dot">●</span></span><span class="edition">THE TENNIS CHAPTER</span><span class="club-note">GOOD SPORT. GREAT COMPANY.</span></header>
<main id="main"><section class="hero" aria-labelledby="title"><div class="hero-copy"><p class="eyebrow"><span class="ball" aria-hidden="true"></span>A NEW CHAPTER OF PLAY</p><h1 id="title">This is<br> <i>a test</i></h1><p class="hero-sub">Meet Swing Tennis.<br>Your afternoon starts here.</p>${cta('Explore the Collection')}<div class="hero-foot"><span>FROM THE GREEN TO THE COURT</span><span aria-hidden="true">↓</span></div></div><div class="hero-image">${img('C02','',true)}<span class="image-label">THE AFTERNOON IS YOURS.</span><span class="roundel" aria-hidden="true">LOVE<br><i>the game.</i></span></div></section>
<div class="ribbon" aria-hidden="true"><span>A LITTLE SPORT.</span><span>✳</span><span>A LOT OF SWING.</span><span>✳</span><span>EVERYONE’S INVITED.</span></div>
<section class="chapter section" aria-labelledby="chapter-title"><div class="section-top"><span>01 / THE NEXT CHAPTER</span><span>NEW COURT. FAMILIAR FEELING.</span></div><div class="chapter-heading"><h2 id="chapter-title">More than<br><i>one kind of swing.</i></h2><div><p>Our style has never stayed in one lane. Why should our afternoons?</p><p>From the first tee to the first serve, we’re bringing the same confidence, personality, and sense of community. Meet the next chapter of Swing.</p></div></div><div class="chapter-media"><figure class="lawn">${img('C03')}<figcaption>01 — Good sport starts with good company.</figcaption></figure><div class="chapter-film">${film('V01','A little pause between plays.')}<p class="aside">Same friends.<br>New plans.</p></div></div></section>
<section class="collection section" id="collection" aria-labelledby="collection-title"><div class="section-top"><span>02 / THE COLLECTION</span><span>THREE PIECES. ENDLESS AFTERNOONS.</span></div><div class="collection-heading"><h2 id="collection-title">Meet your<br><i>doubles partners.</i></h2><p>A classic collar. A little vintage sport.<br>The layer you’ll keep close.<br>Consider the afternoon dressed.</p></div><div class="product-grid">${s.products.map((p,i)=>`<article class="product"><div class="product-image"><span class="product-no">0${i+1}</span>${img(p.images[0])}</div><div class="product-title"><h3>${e(p.name)}</h3><span aria-hidden="true">✳</span></div><p>${e(p.description)}</p></article>`).join('')}</div></section>
<section class="apres section" aria-labelledby="apres-title"><div class="section-top"><span>03 / OFF THE CLOCK</span><span>NO NEED TO CALL IT A DAY.</span></div><div class="apres-grid"><div class="apres-copy"><p class="eyebrow">STAY FOR THE APRÈS.</p><h2 id="apres-title">Good match.<br><i>Better<br>company.</i></h2><p>The best part of the afternoon?<br>Sometimes it starts after the game.</p><p>Keep the polo easy, the jacket close, and your plans open. There’s always time for one more story.</p><span class="handwritten">Let’s stay a little longer.</span></div><div class="apres-media">${film('V03','Nothing on the agenda. Just a little more afternoon.')}<figure class="sunlight">${img('C20')}<figcaption>The golden-hour dress code.</figcaption></figure></div></div></section>
<section class="closing" aria-labelledby="closing-title"><div class="court" aria-hidden="true"></div><p class="eyebrow">SAME SWING. NEXT CHAPTER.</p><h2 id="closing-title">See you<br><i>on court.</i></h2><p>Bring your game. Bring your people.</p>${cta('Explore Swing Tennis')}<span class="closing-signature">With love, Swing.</span></section></main><footer><span class="footer-wordmark">swing</span><span>THE TENNIS CHAPTER</span><a href="#title">BACK TO TOP ↑</a></footer></body></html>`;
}
